#!/usr/bin/env python3
"""
Quick setup helper for NSE IPO Breakout Scanner with Telegram integration.
This script helps you configure all necessary environment variables and dependencies.
"""

import os
import sys
import subprocess
from pathlib import Path


def run_command(cmd: str) -> bool:
    """Run a shell command and return success status."""
    try:
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        return result.returncode == 0
    except Exception as e:
        print(f"Error running command: {e}")
        return False


def check_python_version():
    """Check if Python 3.8+ is installed."""
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print("❌ Python 3.8+ is required")
        print(f"   Current version: {version.major}.{version.minor}.{version.micro}")
        return False
    print(f"✅ Python {version.major}.{version.minor}.{version.micro} found")
    return True


def install_dependencies():
    """Install required Python packages."""
    print("\n📦 Installing Python dependencies...")
    packages = [
        "yfinance",
        "pandas",
        "requests",
        "anthropic",
    ]
    
    cmd = f"pip install {' '.join(packages)}"
    
    if run_command(cmd):
        print("✅ All dependencies installed successfully!")
        return True
    else:
        print("❌ Failed to install dependencies")
        print("   Try running manually: pip install " + " ".join(packages))
        return False


def get_user_input(prompt: str, default: str = "") -> str:
    """Get input from user with optional default."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    value = input(prompt).strip()
    return value if value else default


def setup_api_keys():
    """Guide user through API key setup."""
    print("\n🔑 API KEY CONFIGURATION")
    print("=" * 60)
    
    # Anthropic API Key
    print("\n1️⃣  ANTHROPIC API KEY (for news sentiment)")
    print("   Get it from: https://console.anthropic.com/")
    anthropic_key = get_user_input("   Enter your Anthropic API key (or press Enter to skip)", 
                                    os.environ.get("ANTHROPIC_API_KEY", ""))
    
    # Telegram Setup
    print("\n2️⃣  TELEGRAM BOT TOKEN")
    print("   Get it from: Open Telegram and chat with @BotFather")
    print("   • Type /newbot and follow instructions")
    print("   • BotFather will give you a token like: 123456789:ABCDefgh...")
    telegram_token = get_user_input("   Enter your Telegram Bot Token (or press Enter to skip)", 
                                     os.environ.get("TELEGRAM_BOT_TOKEN", ""))
    
    print("\n3️⃣  TELEGRAM CHAT ID")
    print("   Get it from: Open Telegram and chat with @userinfobot")
    print("   • It will immediately show your Chat ID")
    telegram_chat = get_user_input("   Enter your Telegram Chat ID (or press Enter to skip)", 
                                    os.environ.get("TELEGRAM_CHAT_ID", ""))
    
    return {
        "ANTHROPIC_API_KEY": anthropic_key,
        "TELEGRAM_BOT_TOKEN": telegram_token,
        "TELEGRAM_CHAT_ID": telegram_chat,
    }


def save_env_file(env_vars: dict):
    """Save environment variables to .env file."""
    env_content = """# NSE IPO Breakout Scanner Environment Variables
# Generated by setup script

"""
    
    for key, value in env_vars.items():
        if value:
            env_content += f"{key}={value}\n"
    
    env_file = Path(".env")
    
    if env_vars.get("ANTHROPIC_API_KEY") or env_vars.get("TELEGRAM_BOT_TOKEN"):
        try:
            env_file.write_text(env_content)
            print(f"\n✅ Environment variables saved to {env_file}")
            print("   You can load them with: source .env (on macOS/Linux)")
            return True
        except Exception as e:
            print(f"\n❌ Failed to save .env file: {e}")
            return False
    
    return False


def show_quick_start(env_vars: dict):
    """Display quick start instructions."""
    print("\n" + "=" * 60)
    print("🚀 SETUP COMPLETE!")
    print("=" * 60)
    
    if env_vars.get("ANTHROPIC_API_KEY"):
        print("\n✅ Anthropic API Key set")
    else:
        print("\n⚠  Anthropic API Key NOT set (news sentiment will be disabled)")
    
    if env_vars.get("TELEGRAM_BOT_TOKEN") and env_vars.get("TELEGRAM_CHAT_ID"):
        print("✅ Telegram is configured")
        print(f"   📱 Chat ID: {env_vars['TELEGRAM_CHAT_ID']}")
    else:
        print("⚠  Telegram NOT configured (reports won't be sent)")
    
    print("\n" + "=" * 60)
    print("📖 NEXT STEPS:")
    print("=" * 60)
    
    shell = os.environ.get("SHELL", "").split("/")[-1] or "bash"
    
    if env_vars.get("ANTHROPIC_API_KEY") or env_vars.get("TELEGRAM_BOT_TOKEN"):
        print("\n1️⃣  Load environment variables (choose one):")
        print(f"    • macOS/Linux: source .env")
        print(f"    • Windows (PowerShell): Get-Content .env | ForEach-Object {{ $_ -split '=' | % {{ if (($_).Count -eq 2) {{ [Environment]::SetEnvironmentVariable($_[0], $_[1]) }} }} }}")
    
    print("\n2️⃣  Run the scanner:")
    print("    python nse_ipo_breakout_scanner_v2.py")
    
    print("\n3️⃣  Check reports:")
    print("    • Console output: Real-time in terminal")
    print("    • CSV file: ipo_signals_YYYYMMDD_HHMM.csv")
    if env_vars.get("TELEGRAM_BOT_TOKEN"):
        print("    • Telegram: Automatic message delivery")
    
    print("\n" + "=" * 60)
    print("📚 MORE HELP:")
    print("=" * 60)
    print("\n  • README.md - Full feature documentation")
    print("  • TELEGRAM_SETUP.md - Detailed Telegram guide")
    print("  • nse_ipo_breakout_scanner_v2.py - Configuration parameters")
    print("\n")


def main():
    """Main setup flow."""
    print("\n" + "=" * 60)
    print("🎯 NSE IPO BREAKOUT SCANNER - SETUP WIZARD")
    print("=" * 60)
    
    # Check Python
    print("\n📌 Checking Python version...")
    if not check_python_version():
        print("\n❌ Setup failed. Please install Python 3.8 or newer.")
        sys.exit(1)
    
    # Install dependencies
    print("\n📌 Installing dependencies...")
    if not install_dependencies():
        print("\n⚠  Some dependencies failed to install. You may need to install them manually.")
    
    # Get API Keys
    env_vars = setup_api_keys()
    
    # Save environment
    has_env_file = save_env_file(env_vars)
    
    # Show manual setup if no .env created
    if not has_env_file:
        print("\n📌 Manual environment setup (if .env not created):")
        
        if env_vars.get("ANTHROPIC_API_KEY"):
            print(f"\n   macOS/Linux:")
            print(f"   export ANTHROPIC_API_KEY={env_vars['ANTHROPIC_API_KEY']}")
            print(f"\n   Windows (CMD):")
            print(f"   set ANTHROPIC_API_KEY={env_vars['ANTHROPIC_API_KEY']}")
        
        if env_vars.get("TELEGRAM_BOT_TOKEN"):
            print(f"\n   macOS/Linux:")
            print(f"   export TELEGRAM_BOT_TOKEN={env_vars['TELEGRAM_BOT_TOKEN']}")
            print(f"   export TELEGRAM_CHAT_ID={env_vars['TELEGRAM_CHAT_ID']}")
            print(f"\n   Windows (CMD):")
            print(f"   set TELEGRAM_BOT_TOKEN={env_vars['TELEGRAM_BOT_TOKEN']}")
            print(f"   set TELEGRAM_CHAT_ID={env_vars['TELEGRAM_CHAT_ID']}")
    
    # Show quick start
    show_quick_start(env_vars)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠  Setup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n\n❌ Unexpected error: {e}")
        sys.exit(1)
